// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=4.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b0001
    0b0001 => { ctx.push_entry(dists, 0, 3, 3); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=1 mask=0b0010
    0b0010 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=0 len=2 mask=0b0011
    0b0011 => { ctx.push_entry(dists, 0, 3, 3); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=1 mask=0b0100
    0b0100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=1 len=2 mask=0b0110
    0b0110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=0 len=3 mask=0b0111
    0b0111 => { ctx.push_entry(dists, 0, 3, 3); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=3 len=1 mask=0b1000
    0b1000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_exit(dists, 3, 0, 3); },
    // start=3 len=2 mask=0b1001
    0b1001 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=3 len=3 mask=0b1011
    0b1011 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=2 mask=0b1100
    0b1100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 0, 3); },
    // start=2 len=3 mask=0b1101
    0b1101 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=3 mask=0b1110
    0b1110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 0, 3); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
