// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=3.
// Distances array lanes: 4.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b001
    0b001 => { ctx.push_entry::<4, 0, 2, 2>(dists); ctx.push_v::<0>(); ctx.push_exit::<4, 0, 1, 0>(dists); },
    // start=1 len=1 mask=0b010
    0b010 => { ctx.push_entry::<4, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_exit::<4, 1, 2, 1>(dists); },
    // start=0 len=2 mask=0b011
    0b011 => { ctx.push_entry::<4, 0, 2, 2>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<4, 1, 2, 1>(dists); },
    // start=2 len=1 mask=0b100
    0b100 => { ctx.push_entry::<4, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_exit::<4, 2, 0, 2>(dists); },
    // start=2 len=2 mask=0b101
    0b101 => { ctx.push_entry::<4, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<0>(); ctx.push_exit::<4, 0, 1, 0>(dists); },
    // start=1 len=2 mask=0b110
    0b110 => { ctx.push_entry::<4, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<4, 2, 0, 2>(dists); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
