// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=6.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b000001
    0b000001 => { ctx.push_entry(dists, 0, 5, 5); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=1 mask=0b000010
    0b000010 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=0 len=2 mask=0b000011
    0b000011 => { ctx.push_entry(dists, 0, 5, 5); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=1 mask=0b000100
    0b000100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=1 len=2 mask=0b000110
    0b000110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=0 len=3 mask=0b000111
    0b000111 => { ctx.push_entry(dists, 0, 5, 5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=3 len=1 mask=0b001000
    0b001000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=2 len=2 mask=0b001100
    0b001100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=1 len=3 mask=0b001110
    0b001110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=0 len=4 mask=0b001111
    0b001111 => { ctx.push_entry(dists, 0, 5, 5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=4 len=1 mask=0b010000
    0b010000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=3 len=2 mask=0b011000
    0b011000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=2 len=3 mask=0b011100
    0b011100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=1 len=4 mask=0b011110
    0b011110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=0 len=5 mask=0b011111
    0b011111 => { ctx.push_entry(dists, 0, 5, 5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=5 len=1 mask=0b100000
    0b100000 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_exit(dists, 5, 0, 5); },
    // start=5 len=2 mask=0b100001
    0b100001 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=5 len=3 mask=0b100011
    0b100011 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=5 len=4 mask=0b100111
    0b100111 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=5 len=5 mask=0b101111
    0b101111 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=4 len=2 mask=0b110000
    0b110000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 0, 5); },
    // start=4 len=3 mask=0b110001
    0b110001 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=4 len=4 mask=0b110011
    0b110011 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=4 len=5 mask=0b110111
    0b110111 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=3 len=3 mask=0b111000
    0b111000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 0, 5); },
    // start=3 len=4 mask=0b111001
    0b111001 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=3 len=5 mask=0b111011
    0b111011 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=4 mask=0b111100
    0b111100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 0, 5); },
    // start=2 len=5 mask=0b111101
    0b111101 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=5 mask=0b111110
    0b111110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 0, 5); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
