// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=3.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b001
    0b001 => { ctx.push_entry(dists, 0, 2, 2); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=1 mask=0b010
    0b010 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=0 len=2 mask=0b011
    0b011 => { ctx.push_entry(dists, 0, 2, 2); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=1 mask=0b100
    0b100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_exit(dists, 2, 0, 2); },
    // start=2 len=2 mask=0b101
    0b101 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=2 mask=0b110
    0b110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 0, 2); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
