// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=8.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b00000001
    0b00000001 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=1 mask=0b00000010
    0b00000010 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=0 len=2 mask=0b00000011
    0b00000011 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=1 mask=0b00000100
    0b00000100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=1 len=2 mask=0b00000110
    0b00000110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=0 len=3 mask=0b00000111
    0b00000111 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=3 len=1 mask=0b00001000
    0b00001000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=2 len=2 mask=0b00001100
    0b00001100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=1 len=3 mask=0b00001110
    0b00001110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=0 len=4 mask=0b00001111
    0b00001111 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=4 len=1 mask=0b00010000
    0b00010000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=3 len=2 mask=0b00011000
    0b00011000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=2 len=3 mask=0b00011100
    0b00011100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=1 len=4 mask=0b00011110
    0b00011110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=0 len=5 mask=0b00011111
    0b00011111 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=5 len=1 mask=0b00100000
    0b00100000 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=4 len=2 mask=0b00110000
    0b00110000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=3 len=3 mask=0b00111000
    0b00111000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=2 len=4 mask=0b00111100
    0b00111100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=1 len=5 mask=0b00111110
    0b00111110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=0 len=6 mask=0b00111111
    0b00111111 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=6 len=1 mask=0b01000000
    0b01000000 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=5 len=2 mask=0b01100000
    0b01100000 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=4 len=3 mask=0b01110000
    0b01110000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=3 len=4 mask=0b01111000
    0b01111000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=2 len=5 mask=0b01111100
    0b01111100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=1 len=6 mask=0b01111110
    0b01111110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=0 len=7 mask=0b01111111
    0b01111111 => { ctx.push_entry(dists, 0, 7, 7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_exit(dists, 6, 7, 6); },
    // start=7 len=1 mask=0b10000000
    0b10000000 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=7 len=2 mask=0b10000001
    0b10000001 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=7 len=3 mask=0b10000011
    0b10000011 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=7 len=4 mask=0b10000111
    0b10000111 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=7 len=5 mask=0b10001111
    0b10001111 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=7 len=6 mask=0b10011111
    0b10011111 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=7 len=7 mask=0b10111111
    0b10111111 => { ctx.push_entry(dists, 7, 6, 6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_exit(dists, 5, 6, 5); },
    // start=6 len=2 mask=0b11000000
    0b11000000 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=6 len=3 mask=0b11000001
    0b11000001 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=6 len=4 mask=0b11000011
    0b11000011 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=6 len=5 mask=0b11000111
    0b11000111 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=6 len=6 mask=0b11001111
    0b11001111 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=6 len=7 mask=0b11011111
    0b11011111 => { ctx.push_entry(dists, 6, 5, 5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_exit(dists, 4, 5, 4); },
    // start=5 len=3 mask=0b11100000
    0b11100000 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=5 len=4 mask=0b11100001
    0b11100001 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=5 len=5 mask=0b11100011
    0b11100011 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=5 len=6 mask=0b11100111
    0b11100111 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=5 len=7 mask=0b11101111
    0b11101111 => { ctx.push_entry(dists, 5, 4, 4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_exit(dists, 3, 4, 3); },
    // start=4 len=4 mask=0b11110000
    0b11110000 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=4 len=5 mask=0b11110001
    0b11110001 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=4 len=6 mask=0b11110011
    0b11110011 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=4 len=7 mask=0b11110111
    0b11110111 => { ctx.push_entry(dists, 4, 3, 3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_v(2); ctx.push_exit(dists, 2, 3, 2); },
    // start=3 len=5 mask=0b11111000
    0b11111000 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=3 len=6 mask=0b11111001
    0b11111001 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=3 len=7 mask=0b11111011
    0b11111011 => { ctx.push_entry(dists, 3, 2, 2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_v(1); ctx.push_exit(dists, 1, 2, 1); },
    // start=2 len=6 mask=0b11111100
    0b11111100 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    // start=2 len=7 mask=0b11111101
    0b11111101 => { ctx.push_entry(dists, 2, 1, 1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_v(0); ctx.push_exit(dists, 0, 1, 0); },
    // start=1 len=7 mask=0b11111110
    0b11111110 => { ctx.push_entry(dists, 1, 0, 0); ctx.push_v(1); ctx.push_v(2); ctx.push_v(3); ctx.push_v(4); ctx.push_v(5); ctx.push_v(6); ctx.push_v(7); ctx.push_exit(dists, 7, 0, 7); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
