// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=4.
// Distances array lanes: 4.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b0001
    0b0001 => { ctx.push_entry::<4, 0, 3, 3>(dists); ctx.push_v::<0>(); ctx.push_exit::<4, 0, 1, 0>(dists); },
    // start=1 len=1 mask=0b0010
    0b0010 => { ctx.push_entry::<4, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_exit::<4, 1, 2, 1>(dists); },
    // start=0 len=2 mask=0b0011
    0b0011 => { ctx.push_entry::<4, 0, 3, 3>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<4, 1, 2, 1>(dists); },
    // start=2 len=1 mask=0b0100
    0b0100 => { ctx.push_entry::<4, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_exit::<4, 2, 3, 2>(dists); },
    // start=1 len=2 mask=0b0110
    0b0110 => { ctx.push_entry::<4, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<4, 2, 3, 2>(dists); },
    // start=0 len=3 mask=0b0111
    0b0111 => { ctx.push_entry::<4, 0, 3, 3>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<4, 2, 3, 2>(dists); },
    // start=3 len=1 mask=0b1000
    0b1000 => { ctx.push_entry::<4, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_exit::<4, 3, 0, 3>(dists); },
    // start=3 len=2 mask=0b1001
    0b1001 => { ctx.push_entry::<4, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<0>(); ctx.push_exit::<4, 0, 1, 0>(dists); },
    // start=3 len=3 mask=0b1011
    0b1011 => { ctx.push_entry::<4, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<4, 1, 2, 1>(dists); },
    // start=2 len=2 mask=0b1100
    0b1100 => { ctx.push_entry::<4, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<4, 3, 0, 3>(dists); },
    // start=2 len=3 mask=0b1101
    0b1101 => { ctx.push_entry::<4, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<0>(); ctx.push_exit::<4, 0, 1, 0>(dists); },
    // start=1 len=3 mask=0b1110
    0b1110 => { ctx.push_entry::<4, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<4, 3, 0, 3>(dists); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
