// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=7.
// Distances array lanes: 8.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b0000001
    0b0000001 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=1 len=1 mask=0b0000010
    0b0000010 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=0 len=2 mask=0b0000011
    0b0000011 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=2 len=1 mask=0b0000100
    0b0000100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=1 len=2 mask=0b0000110
    0b0000110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=0 len=3 mask=0b0000111
    0b0000111 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=3 len=1 mask=0b0001000
    0b0001000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=2 len=2 mask=0b0001100
    0b0001100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=1 len=3 mask=0b0001110
    0b0001110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=0 len=4 mask=0b0001111
    0b0001111 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=4 len=1 mask=0b0010000
    0b0010000 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=3 len=2 mask=0b0011000
    0b0011000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=2 len=3 mask=0b0011100
    0b0011100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=1 len=4 mask=0b0011110
    0b0011110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=0 len=5 mask=0b0011111
    0b0011111 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=5 len=1 mask=0b0100000
    0b0100000 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=4 len=2 mask=0b0110000
    0b0110000 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=3 len=3 mask=0b0111000
    0b0111000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=2 len=4 mask=0b0111100
    0b0111100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=1 len=5 mask=0b0111110
    0b0111110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=0 len=6 mask=0b0111111
    0b0111111 => { ctx.push_entry::<8, 0, 6, 6>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_exit::<8, 5, 6, 5>(dists); },
    // start=6 len=1 mask=0b1000000
    0b1000000 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    // start=6 len=2 mask=0b1000001
    0b1000001 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=6 len=3 mask=0b1000011
    0b1000011 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=6 len=4 mask=0b1000111
    0b1000111 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=6 len=5 mask=0b1001111
    0b1001111 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=6 len=6 mask=0b1011111
    0b1011111 => { ctx.push_entry::<8, 6, 5, 5>(dists); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 5, 4>(dists); },
    // start=5 len=2 mask=0b1100000
    0b1100000 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    // start=5 len=3 mask=0b1100001
    0b1100001 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=5 len=4 mask=0b1100011
    0b1100011 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=5 len=5 mask=0b1100111
    0b1100111 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=5 len=6 mask=0b1101111
    0b1101111 => { ctx.push_entry::<8, 5, 4, 4>(dists); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=4 len=3 mask=0b1110000
    0b1110000 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    // start=4 len=4 mask=0b1110001
    0b1110001 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=4 len=5 mask=0b1110011
    0b1110011 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=4 len=6 mask=0b1110111
    0b1110111 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=3 len=4 mask=0b1111000
    0b1111000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    // start=3 len=5 mask=0b1111001
    0b1111001 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=3 len=6 mask=0b1111011
    0b1111011 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=2 len=5 mask=0b1111100
    0b1111100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    // start=2 len=6 mask=0b1111101
    0b1111101 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=1 len=6 mask=0b1111110
    0b1111110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<5>(); ctx.push_v::<6>(); ctx.push_exit::<8, 6, 0, 6>(dists); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
