// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// Jump-table match arms for convex clipping, N=5.
// Distances array lanes: 8.
//
// Each case corresponds to a single contiguous run of inside vertices (cyclic).

match mask {
    // start=0 len=1 mask=0b00001
    0b00001 => { ctx.push_entry::<8, 0, 4, 4>(dists); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=1 len=1 mask=0b00010
    0b00010 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=0 len=2 mask=0b00011
    0b00011 => { ctx.push_entry::<8, 0, 4, 4>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=2 len=1 mask=0b00100
    0b00100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=1 len=2 mask=0b00110
    0b00110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=0 len=3 mask=0b00111
    0b00111 => { ctx.push_entry::<8, 0, 4, 4>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=3 len=1 mask=0b01000
    0b01000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=2 len=2 mask=0b01100
    0b01100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=1 len=3 mask=0b01110
    0b01110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=0 len=4 mask=0b01111
    0b01111 => { ctx.push_entry::<8, 0, 4, 4>(dists); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_exit::<8, 3, 4, 3>(dists); },
    // start=4 len=1 mask=0b10000
    0b10000 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 0, 4>(dists); },
    // start=4 len=2 mask=0b10001
    0b10001 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=4 len=3 mask=0b10011
    0b10011 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=4 len=4 mask=0b10111
    0b10111 => { ctx.push_entry::<8, 4, 3, 3>(dists); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_exit::<8, 2, 3, 2>(dists); },
    // start=3 len=2 mask=0b11000
    0b11000 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 0, 4>(dists); },
    // start=3 len=3 mask=0b11001
    0b11001 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=3 len=4 mask=0b11011
    0b11011 => { ctx.push_entry::<8, 3, 2, 2>(dists); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_v::<1>(); ctx.push_exit::<8, 1, 2, 1>(dists); },
    // start=2 len=3 mask=0b11100
    0b11100 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 0, 4>(dists); },
    // start=2 len=4 mask=0b11101
    0b11101 => { ctx.push_entry::<8, 2, 1, 1>(dists); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_v::<0>(); ctx.push_exit::<8, 0, 1, 0>(dists); },
    // start=1 len=4 mask=0b11110
    0b11110 => { ctx.push_entry::<8, 1, 0, 0>(dists); ctx.push_v::<1>(); ctx.push_v::<2>(); ctx.push_v::<3>(); ctx.push_v::<4>(); ctx.push_exit::<8, 4, 0, 4>(dists); },
    _ => return fallback(ctx.poly, ctx.hp, ctx.out),
}
