// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// (start,len) lookup table for contiguous inside runs, N=3.
//
// Entry is (0,0) for:
// - mask==0 (all outside)
// - mask==full (all inside)
// - non-contiguous/disconnected masks (should be impossible for convex clip)

pub(super) const TABLE_N3: [(u8, u8); 8] = [
    (0u8, 0u8), // 0b000
    (0u8, 1u8), // 0b001
    (1u8, 1u8), // 0b010
    (0u8, 2u8), // 0b011
    (2u8, 1u8), // 0b100
    (2u8, 2u8), // 0b101
    (1u8, 2u8), // 0b110
    (0u8, 0u8), // 0b111
];
