// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// (start,len) lookup table for contiguous inside runs, N=4.
//
// Entry is (0,0) for:
// - mask==0 (all outside)
// - mask==full (all inside)
// - non-contiguous/disconnected masks (should be impossible for convex clip)

pub(super) const TABLE_N4: [(u8, u8); 16] = [
    (0u8, 0u8), // 0b0000
    (0u8, 1u8), // 0b0001
    (1u8, 1u8), // 0b0010
    (0u8, 2u8), // 0b0011
    (2u8, 1u8), // 0b0100
    (0u8, 0u8), // 0b0101
    (1u8, 2u8), // 0b0110
    (0u8, 3u8), // 0b0111
    (3u8, 1u8), // 0b1000
    (3u8, 2u8), // 0b1001
    (0u8, 0u8), // 0b1010
    (3u8, 3u8), // 0b1011
    (2u8, 2u8), // 0b1100
    (2u8, 3u8), // 0b1101
    (1u8, 3u8), // 0b1110
    (0u8, 0u8), // 0b1111
];
