// @generated by `scripts/gen_clip_tables.py`; do not edit by hand.
// (start,len) lookup table for contiguous inside runs, N=5.
//
// Entry is (0,0) for:
// - mask==0 (all outside)
// - mask==full (all inside)
// - non-contiguous/disconnected masks (should be impossible for convex clip)

pub(super) const TABLE_N5: [(u8, u8); 32] = [
    (0u8, 0u8), // 0b00000
    (0u8, 1u8), // 0b00001
    (1u8, 1u8), // 0b00010
    (0u8, 2u8), // 0b00011
    (2u8, 1u8), // 0b00100
    (0u8, 0u8), // 0b00101
    (1u8, 2u8), // 0b00110
    (0u8, 3u8), // 0b00111
    (3u8, 1u8), // 0b01000
    (0u8, 0u8), // 0b01001
    (0u8, 0u8), // 0b01010
    (0u8, 0u8), // 0b01011
    (2u8, 2u8), // 0b01100
    (0u8, 0u8), // 0b01101
    (1u8, 3u8), // 0b01110
    (0u8, 4u8), // 0b01111
    (4u8, 1u8), // 0b10000
    (4u8, 2u8), // 0b10001
    (0u8, 0u8), // 0b10010
    (4u8, 3u8), // 0b10011
    (0u8, 0u8), // 0b10100
    (0u8, 0u8), // 0b10101
    (0u8, 0u8), // 0b10110
    (4u8, 4u8), // 0b10111
    (3u8, 2u8), // 0b11000
    (3u8, 3u8), // 0b11001
    (0u8, 0u8), // 0b11010
    (3u8, 4u8), // 0b11011
    (2u8, 3u8), // 0b11100
    (2u8, 4u8), // 0b11101
    (1u8, 4u8), // 0b11110
    (0u8, 0u8), // 0b11111
];
